example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register 
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import show_create_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/',show_wishlist_ajax,name='show_wishlist_ajax'),
    path('ajax/submit', show_create_wishlist, name='show_create_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class ItemWishlist(models.Model):
    item_name = models.CharField(max_length=50)
    item_price = models.IntegerField()
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import ItemWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_wishlist_item = ItemWishlist.objects.all()
    context = {
        'list_item': data_wishlist_item,
        'name': 'Maureen',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_wishlist_item = ItemWishlist.objects.all()
    context = {
        'list_item': data_wishlist_item,
        'name': 'Maureen',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html",context)

@login_required(login_url='login/')
@csrf_exempt
def show_create_wishlist(request):
    if request.method == 'POST':
        item_name = request.POST.get('item_name')
        item_price = request.POST.get('item_price')
        description = request.POST.get('description')
        ItemWishlist.objects.create(item_name=item_name,description=description,item_price=item_price)
        response = HttpResponseRedirect(reverse("wishlist:show_wishlist_ajax")) 
        return response

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn btn-outline-secondary login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <!-- <td><input type="submit" name="submit" value="Daftar"/></td>   -->
                    <td><button class="btn btn-outline-secondary">Daftar</button></td>
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Maureen</a>
        <div class="" id="navbarSupportedContent">
        <a href="{% url 'wishlist:logout' %}"><button class="btn btn-outline-secondary">Logout</button></a>
    </div>
</nav>

<div class="wishlist-body">
    <h5>Name: </h5>
    <p>{{name}}</p>

    <table class="table wishlist-table">
        <tr class="table-light">
            <th>Item Name</th>
            <th>Item Price</th>
            <th>Description</th>
        </tr>
        {% comment %} Add the data below this line {% endcomment %}
        {% for item in list_item %}
        <tr>
            <td>{{item.item_name}}</td>
            <td>{{item.item_price}}</td>
            <td>{{item.description}}</td>
        </tr>
        {% endfor %}
    </table>

    <h5>Sesi terakhir login: {{ last_login }}</h5>

    <a href="{% url 'wishlist:logout' %}"><button class="btn btn-outline-secondary">Logout</button></a>

</div>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %} {% block content %}
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
  $(document).ready(function(){
      $.get("/wishlist/json", function(data) {

        for (i=0;i<data.length;i++){

          $(".barang").append(
            `<tr>
                <td>${data[i].fields.item_name}</td>
                <td>${data[i].fields.item_price}</td>
                <td>${data[i].fields.description}</td>
            </tr>`
            )
      
        }

      });

      $("#submit_btn").click(function(){
      $.post(
        "/wishlist/ajax/submit", 
        {
            item_name: $("#item_name").val(),
            item_price:parseInt($("#item_price").val()),
            description:$("#description").val()
        } 
        )
      $(".barang").append(
        `<tr>
            <td>${$("#item_name").val()}</td>
            <td>${parseInt($("#item_price").val())}</td>
            <td>${$("#description").val()}</td>
        </tr>`
        )
      })
  });
  </script>
</head>
<div>
  <nav class="navbar navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{name}}</a>   
      <button class="btn btn-outline-secondary" type="submit" onclick="location.href=`{% url 'wishlist:logout' %}`">Logout</button>
    </form>
  </div>
</nav>

<form method="POST" action="" onsubmit="return false;">
  {% csrf_token %}
  <table>
    <tr>
      <td>Nama Barang:</td>
      <td>
        <input
          type="text"
          name="item_name"
          placeholder="Nama Barang"
          id="item_name"
          class="form-control"
        />
      </td>
    </tr>

    <tr>
      <td>Harga Barang:</td>
      <td>
        <input
          type="text"
          name="item_price"
          id="item_price"
          placeholder="Harga Barang"
          class="form-control"
        />
      </td>
    </tr>
    <tr>
      <td>Deskripsi:</td>
      <td>
        <input
          type="text"
          name="description"
          placeholder="Deskripsi"
          class="form-control"
          id="description"
        />
      </td>
    </tr>

    <tr>
      <td></td>
    <td><button id="submit_btn" class="btn btn-outline-secondary">Add new wishlist</button></td>    </tr>
  </table>
</form>

<div class="mt-3 px-5" >
  <h5>Sesi terakhir login: {{ last_login }}</h5>
<table class="barang">
  <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
  </tr>

</table>
</div>
</div>



{% endblock content %}